name: build-test

on:
  pull-request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
      steps:
        - uses: actions/checkout@2
        - name: Setup Node 16
          uses: actions/setup-node@2
          with:
            node-version: 16.x
        - run: npm install
        - run: npm run lint
